Ydelsesberegner.Admin/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Newtonsoft.Json;
using Ydelsesberegner.Admin.Models;
using Ydelsesberegner.Admin.ViewModels;

namespace Ydelsesberegner.Admin.Controllers
{
    public class JobsController : Controller
    {
        private readonly YdelsesberegnerContext db = new YdelsesberegnerContext();

        public ActionResult Index(int? applicationId)
        {
            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", applicationId ?? (db.Application.FirstOrDefault() != null ? db.Application.First().ApplicationId : 0));

            return View();
        }

        public ActionResult Create(int? applicationId)
        {
            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", applicationId);

            var jobViewModel = new JobViewModel { MonthlyWorkHours = 160.33M };

            return View("JobForm", jobViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobId,ApplicationId,JobTitle,MonthlySalary,MonthlyWorkHours")] JobViewModel jobViewModel)
        {
            if (ModelState.IsValid)
            {
                var job_db = Mapper.Map<Job>(jobViewModel);

                db.Job.Add(job_db);
                db.SaveChanges();

                return RedirectToAction("Index", new { applicationId = job_db.ApplicationId });
            }

            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", jobViewModel.ApplicationId);

            return View("JobForm", jobViewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Job job_db = db.Job.Find(id);

            if (job_db == null)
            {
                return HttpNotFound();
            }

            var jobViewModel = Mapper.Map<JobViewModel>(job_db);

            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", job_db.ApplicationId);

            return View("JobForm", jobViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobId,ApplicationId,JobTitle,MonthlySalary,MonthlyWorkHours")] JobViewModel jobViewModel)
        {
            if (ModelState.IsValid)
            {
                var job_db = Mapper.Map<Job>(jobViewModel);

                db.Entry(job_db).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index", new { applicationId = job_db.ApplicationId });
            }

            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", jobViewModel.ApplicationId);

            return View("JobForm", jobViewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Ydelsesberegner.Admin/Views/Shared/_Layout.cshtml
@using Ydelsesberegner.Admin.Classes
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Syddjurs Kommune | Ydelsesberegner -> Administration -> @ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("header", required: false)
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Administration", "Index", "Jobs", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div id="bs-example-navbar-collapse-1" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Beregnere", "Index", "Applications")</li>
                    <li>@Html.ActionLink("Ydelsestyper", "Index", "BenefitTypes")</li>
                    <li>@Html.ActionLink("Slides", "Index", "Slides")</li>
                    <li>@Html.ActionLink("Jobs", "Index", "Jobs")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" ng-app="ydelsesberegnerAdminApp">
        @RenderBody()
        <hr />
        <footer>
            <div class="col-xs-12">
                <div class="pull-right">Du er logget ind som: @UserInfoHelper.GetDisplayName()</div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/angular-app")
    @Scripts.Render("~/bundles/jquery-datatables")
    @RenderSection("scripts", required: false)
</body>
</html>