Ydelsesberegner.Admin/Models/Application.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ydelsesberegner.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.BenefitType = new HashSet<BenefitType>();
            this.Job = new HashSet<Job>();
            this.Slide = new HashSet<Slide>();
        }
    
        public int ApplicationId { get; set; }
        public string Name { get; set; }
        public string ResultViewPath { get; set; }
        public string ActionName { get; set; }
        public string PrintActionName { get; set; }
        public string Layout { get; set; }
        public string Url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenefitType> BenefitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slide> Slide { get; set; }
    }
}

Ydelsesberegner.Admin/Models/Condition.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ydelsesberegner.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public int ConditionId { get; set; }
        public int QuestionId { get; set; }
        public int AnswerId { get; set; }
        public Nullable<int> SlideId { get; set; }
        public Nullable<int> BenefitTypeId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual BenefitType BenefitType { get; set; }
        public virtual Question Question { get; set; }
        public virtual Slide Slide { get; set; }
    }
}

Ydelsesberegner.Admin/Controllers/AttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Ydelsesberegner.Admin.Models;
using Ydelsesberegner.Admin.ViewModels;

namespace Ydelsesberegner.Admin.Controllers
{
    public class AttachmentsController : Controller
    {
        public static void CreateAttachments(int slideId, IEnumerable<HttpPostedFileBase> files)
        {
            DeleteAttachments(slideId);

            using (var db = new YdelsesberegnerContext())
            {
                foreach (var file in files)
                {
                    MemoryStream target = new MemoryStream();

                    file.InputStream.CopyTo(target);

                    byte[] data = target.ToArray();

                    var attachmentViewModel = new AttachmentViewModel
                    {
                        SlideId = slideId,
                        FileName = file.FileName,
                        FileType = file.ContentType,
                        FileContent = data

                    };

                    var attachment = Mapper.Map<Attachment>(attachmentViewModel);

                    db.Attachment.Add(attachment);
                    db.SaveChanges();
                }

            }
        }

        public ActionResult DownloadAttachment(int attachmentId)
        {
            using (var db = new YdelsesberegnerContext())
            {
                var attachment = db.Attachment.SingleOrDefault(a => a.AttachmentId == attachmentId);

                if (attachment == null)
                {
                    return HttpNotFound();
                }

                byte[] fileBytes = attachment.FileContent;
                string fileName = attachment.FileName;

                return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
            }
        }

        public ActionResult DeleteAttachment(int attachmentId)
        {
            using (var db = new YdelsesberegnerContext())
            {
                var attachment = db.Attachment.SingleOrDefault(a => a.AttachmentId == attachmentId);

                if (attachment == null) return HttpNotFound();

                db.Attachment.Remove(attachment);
                db.SaveChanges();

                return RedirectToAction("Edit", "Slides", new {id = attachment.SlideId});
            }
        }

        public static void DeleteAttachments(int slideId)
        {
            using (var db = new YdelsesberegnerContext())
            {
                var existingAttachmenets = db.Slide.Single(s => s.SlideId == slideId).Attachment;

                if (existingAttachmenets.Any())
                {
                    db.Attachment.RemoveRange(existingAttachmenets);
                }

                db.SaveChanges();
            }
        }
    }
}

Ydelsesberegner.Admin/Controllers/ConditionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Ydelsesberegner.Admin.Models;
using Ydelsesberegner.Admin.ViewModels;

namespace Ydelsesberegner.Admin.Controllers
{
    public class ConditionsController : Controller
    {
        public static void CreateConditions(int? slideId, int? benefitTypeId, List<ConditionViewModel> conditions)
        {
            DeleteConditions(slideId, benefitTypeId);

            using (var db = new YdelsesberegnerContext())
            {
                foreach (var c in conditions.ToList())
                {
                    var condition = Mapper.Map<Condition>(c);

                    if (slideId.HasValue) { condition.SlideId = slideId; }
                    if (benefitTypeId.HasValue) { condition.BenefitTypeId = benefitTypeId; }

                    db.Condition.Add(condition);
                }

                db.SaveChanges();
            }
        }
        public static void DeleteConditions(int? slideId, int? benefitTypeId)
        {
            using (var db = new YdelsesberegnerContext())
            {
                var existingConditions = slideId.HasValue ? db.Condition.Where(c => c.SlideId == slideId) : db.Condition.Where(c => c.BenefitTypeId == benefitTypeId);

                if (existingConditions.Any())
                {
                    db.Condition.RemoveRange(existingConditions);
                }

                db.SaveChanges();
            }
        }
    }
}

Ydelsesberegner.Admin/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Newtonsoft.Json;
using Ydelsesberegner.Admin.Models;
using Ydelsesberegner.Admin.ViewModels;

namespace Ydelsesberegner.Admin.Controllers
{
    public class JobsController : Controller
    {
        private readonly YdelsesberegnerContext db = new YdelsesberegnerContext();

        public ActionResult Index(int? applicationId)
        {
            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", applicationId ?? (db.Application.FirstOrDefault() != null ? db.Application.First().ApplicationId : 0));

            return View();
        }

        public ActionResult Create(int? applicationId)
        {
            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", applicationId);

            var jobViewModel = new JobViewModel { MonthlyWorkHours = 160.33M };

            return View("JobForm", jobViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobId,ApplicationId,JobTitle,MonthlySalary,MonthlyWorkHours")] JobViewModel jobViewModel)
        {
            if (ModelState.IsValid)
            {
                var job_db = Mapper.Map<Job>(jobViewModel);

                db.Job.Add(job_db);
                db.SaveChanges();

                return RedirectToAction("Index", new { applicationId = job_db.ApplicationId });
            }

            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", jobViewModel.ApplicationId);

            return View("JobForm", jobViewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Job job_db = db.Job.Find(id);

            if (job_db == null)
            {
                return HttpNotFound();
            }

            var jobViewModel = Mapper.Map<JobViewModel>(job_db);

            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", job_db.ApplicationId);

            return View("JobForm", jobViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobId,ApplicationId,JobTitle,MonthlySalary,MonthlyWorkHours")] JobViewModel jobViewModel)
        {
            if (ModelState.IsValid)
            {
                var job_db = Mapper.Map<Job>(jobViewModel);

                db.Entry(job_db).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index", new { applicationId = job_db.ApplicationId });
            }

            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", jobViewModel.ApplicationId);

            return View("JobForm", jobViewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Ydelsesberegner.Admin/Controllers/SlidesController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Ydelsesberegner.Admin.Models;
using Ydelsesberegner.Admin.ViewModels;

namespace Ydelsesberegner.Admin.Controllers
{
    public class SlidesController : Controller
    {
        private readonly YdelsesberegnerContext db = new YdelsesberegnerContext();

        public ActionResult Index(int? applicationId)
        {
            ViewBag.Applications = new SelectList(db.Application.Select(a => new { a.ApplicationId, a.Name }), "ApplicationId", "Name", applicationId ?? (db.Application.FirstOrDefault() != null ? db.Application.First().ApplicationId : 0));

            return View();
        }
        public ActionResult Create(int? applicationId)
        {
            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", applicationId);

            var slide = new SlideViewModel { DisplayNextButton = true };

            return View("SlideForm", slide);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Slide slide_db = db.Slide.Find(id);

            if (slide_db == null) return HttpNotFound();

            SlideViewModel slideViewModel = Mapper.Map<SlideViewModel>(slide_db);

            slideViewModel.Question = Mapper.Map<QuestionViewModel>(slide_db.Question.FirstOrDefault());

            ViewBag.Attachments = Mapper.Map<List<AttachmentViewModel>>(slide_db.Attachment.ToList());
            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", slideViewModel.ApplicationId);

            return View("SlideForm", slideViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SlideId,SlideGUID,ApplicationId,SlideOrderIndex,SlideName,SlideHeadline,SlideText,IsResultSlide,DisplayPrintButton,DisplayNextButton,DisplayReturnToStartButton,DisplayTextBox,Question,Condition,Attachment")] SlideViewModel slideViewModel)
        {
            if (ModelState.IsValid)
            {
                var slide_db = Mapper.Map<Slide>(slideViewModel);

                slide_db.SlideOrderIndex = db.Slide.Any(s => s.ApplicationId == slideViewModel.ApplicationId) ? db.Slide.Where(s => s.ApplicationId == slideViewModel.ApplicationId).Max(s => s.SlideOrderIndex) + 1 : 0;

                db.Slide.Add(slide_db);
                db.SaveChanges();

                slideViewModel.SlideId = slide_db.SlideId;

                if (!string.IsNullOrWhiteSpace(slideViewModel.Question?.QuestionSystemName))
                {
                    CreateOrUpdateQuestion(slide_db.SlideId, slideViewModel.Question);
                }

                if (slideViewModel.Condition != null)
                {
                    ConditionsController.CreateConditions(slide_db.SlideId, null, slideViewModel.Condition.ToList());
                }

                if (slideViewModel.Attachment != null && slideViewModel.Attachment.Any(a => a != null))
                {
                    AttachmentsController.CreateAttachments(slide_db.SlideId, slideViewModel.Attachment);
                }

                return RedirectToAction("Index", new { applicationId = slideViewModel.ApplicationId });
            }

            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", slideViewModel.ApplicationId);

            return View("SlideForm", slideViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SlideId,SlideGUID,ApplicationId,SlideOrderIndex,SlideName,SlideHeadline,SlideText,IsResultSlide,DisplayPrintButton,DisplayNextButton,DisplayReturnToStartButton,DisplayTextBox,Question,Condition,Attachment")] SlideViewModel slideViewModel)
        {
            if (ModelState.IsValid)
            {
                var slide_db = Mapper.Map<Slide>(slideViewModel);

                db.Entry(slide_db).State = EntityState.Modified;
                db.SaveChanges();

                if (!string.IsNullOrWhiteSpace(slideViewModel.Question?.QuestionSystemName))
                {
                    CreateOrUpdateQuestion(slide_db.SlideId, slideViewModel.Question);
                }

                if (slideViewModel.Condition != null)
                {
                    ConditionsController.CreateConditions(slide_db.SlideId, null, slideViewModel.Condition.ToList());
                }
                else
                {
                    ConditionsController.DeleteConditions(slide_db.SlideId, null);
                }

                if (slideViewModel.Attachment != null && slideViewModel.Attachment.Any(a => a != null))
                {
                    AttachmentsController.CreateAttachments(slide_db.SlideId, slideViewModel.Attachment);
                }

                return RedirectToAction("Index", new { applicationId = slideViewModel.ApplicationId });
            }

            ViewBag.Applications = new SelectList(db.Application, "ApplicationId", "Name", slideViewModel.ApplicationId);

            return View("SlideForm", slideViewModel);
        }

        protected void CreateOrUpdateQuestion(int slideId, QuestionViewModel questionViewModel)
        {
            var question = Mapper.Map<Question>(questionViewModel);

            question.SlideId = slideId;

            if (questionViewModel.QuestionId != 0)
            {
                db.Entry(question).State = EntityState.Modified;

                foreach (var answerViewModel in questionViewModel.Answer)
                {
                    var answer = Mapper.Map<Answer>(answerViewModel);

                    answer.QuestionId = question.QuestionId;

                    if (answerViewModel.AnswerId != 0)
                    {
                        db.Entry(answer).State = EntityState.Modified;
                    }
                    else
                    {
                        db.Answer.Add(answer);
                    }
                }

                db.SaveChanges();
            }
            else
            {
                db.Question.Add(question);
                db.SaveChanges();

                foreach (var answerViewModel in questionViewModel.Answer)
                {
                    var answer = Mapper.Map<Answer>(answerViewModel);

                    answer.QuestionId = question.QuestionId;

                    db.Answer.Add(answer);
                }

                db.SaveChanges();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Ydelsesberegner.Admin/Views/Shared/PartialViews/Forms/_Application.cshtml
@model Ydelsesberegner.Admin.ViewModels.ApplicationViewModel

<div class="form-horizontal">
    @Html.HiddenFor(model => model.ApplicationId)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Layout, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Layout, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Layout, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ResultViewPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ResultViewPath, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ResultViewPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ActionName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ActionName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ActionName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrintActionName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrintActionName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrintActionName, "", new { @class = "text-danger" })
        </div>
    </div>

</div>

Ydelsesberegner.Admin/Views/Shared/PartialViews/Forms/_BenefitType.cshtml
@model Ydelsesberegner.Admin.ViewModels.BenefitTypeViewModel

<div class="form-horizontal">
    @Html.HiddenFor(model => model.BenefitTypeId)

    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationId", (SelectList)ViewBag.Applications, "Vælg applikation", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MonthlyRate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MonthlyRate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MonthlyRate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MonthlyWorkHours, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MonthlyWorkHours, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MonthlyWorkHours, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.MaxLengthMonths, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxLengthMonths, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxLengthMonths, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

Ydelsesberegner.Admin/Views/Shared/PartialViews/Forms/_Conditions.cshtml
<div class="form-horizontal" ng-controller="conditionsController">
    <table id="conditions-table" class="table" ng-form="conditionsForm" style="{{conditions.length == 0 ? 'width: 50%;' : ''}}">
        <thead>
            <tr>
                <th>Spørgsmål</th>
                <th>Svar</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr ng-if="conditions.length == 0">
                <td colspan="3">
                    <button type="button" ng-click="add($index, condition)" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus-sign"></span> Opret betingelse</button>
                </td>
            </tr>
            <tr ng-repeat="condition in conditions track by $index">
                <td>
                    <input type="hidden" ng-model="condition.ConditionId" ng-if="condition.ConditionId" name="Condition[{{$index}}].ConditionId" value="{{condition.ConditionId}}" />
                    <select name="Condition[{{$index}}].QuestionId" ng-model="condition.QuestionId" ng-init="condition.QuestionId = condition.QuestionId || options[0].value" ng-change="questionChange({{$index}}, condition)" class="form-control" convert-to-number>
                        <option value="">Vælg spørgsmål</option>
                        <option ng-repeat="question in questions track by question.QuestionId" value="{{question.QuestionId}}">{{question.QuestionSystemName}}</option>
                    </select>
                </td>
                <td>
                    <select name="Condition[{{$index}}].AnswerId" ng-model="condition.AnswerId" ng-init="condition.AnswerId = condition.AnswerId || options[0].value" class="form-control" convert-to-number>
                        <option value="">Vælg svarmulighed</option>
                        <option ng-repeat="answer in answers[$index] track by answer.AnswerId" value="{{answer.AnswerId}}">{{answer.AnswerText}}</option>
                    </select>
                </td>
                <td>
                    <button type="button" ng-click="add($index, condition)" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus-sign"></span> Opret betingelse</button>
                    <button type="button" ng-click="remove($index, condition)" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-minus-sign"></span> Fjern betingelse</button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

Ydelsesberegner.Admin/Views/Shared/PartialViews/Forms/_Slide.cshtml
@using Ydelsesberegner.Admin.ViewModels
@model Ydelsesberegner.Admin.ViewModels.SlideViewModel

<div class="form-horizontal">
    @Html.HiddenFor(model => model.SlideId)
    @Html.HiddenFor(model => model.SlideOrderIndex)

    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationId", (SelectList)ViewBag.Applications, "Vælg applikation", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SlideName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SlideName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SlideName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SlideHeadline, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SlideHeadline, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SlideHeadline, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Attachment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (ViewBag.Attachments != null && ((List<AttachmentViewModel>)ViewBag.Attachments).Count > 0)
            {
                foreach (var attachment in (List<AttachmentViewModel>)ViewBag.Attachments)
                {
                    <a href="@Url.Action("DownloadAttachment", "Attachments", new {attachmentId = attachment.AttachmentId })">@attachment.FileName</a> <text>|</text> <a href="@Url.Action("DeleteAttachment", "Attachments", new { attachmentId = attachment.AttachmentId })">Slet</a>
                    <br />
                }
            }
            else
            {
                <input type="file" id="Attachment" name="Attachment" multiple />
            }
            @Html.ValidationMessageFor(model => model.Attachment, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsResultSlide, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsResultSlide)
                @Html.ValidationMessageFor(model => model.IsResultSlide, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DisplayNextButton, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.DisplayNextButton)
                @Html.ValidationMessageFor(model => model.DisplayNextButton, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DisplayReturnToStartButton, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.DisplayReturnToStartButton)
                @Html.ValidationMessageFor(model => model.DisplayReturnToStartButton, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DisplayTextBox, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.DisplayTextBox)
                @Html.ValidationMessageFor(model => model.DisplayTextBox, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DisplayPrintButton, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.DisplayPrintButton)
                @Html.ValidationMessageFor(model => model.DisplayPrintButton, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SlideText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.SlideText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SlideText, "", new { @class = "text-danger" })
        </div>
    </div>
</div>